PROVIDERS = {
    "gemini": {
        "label": "Google Gemini",
        "litellm_prefix": "gemini",
        "model_fetch_method": "gemini",
        # Gemini has search grounding, but our litellm path doesn't wire it
        # yet — flip this only together with an LLMService integration.
        "supports_search": False,
        "fields": {
            "api_key": {
                "type": "secret",
                "label": "API Key",
                "env_var": "GEMINI_API_KEY",
                "required": True,
            },
            "storyteller_model": {
                "type": "text",
                "label": "Storyteller Model",
                "default": "gemini/gemini-2.5-flash",
                "description": "Model for narrative generation. Use gemini/ prefix.",
            },
            "storyteller_fallback_models": {
                "type": "text",
                "label": "Fallback Models",
                "default": "",
                "description": "Comma-separated list of backup storyteller models.",
            },
            "reader_model": {
                "type": "text",
                "label": "Reader Model",
                "default": "gemini/gemini-2.5-flash",
                "description": "Model for structured JSON extraction.",
            },
            "embedding_model": {
                "type": "text",
                "label": "Embedding Model",
                "default": "gemini/gemini-embedding-001",
                "description": "Model for vector embeddings. Must support embeddings API.",
            },
            "module_fast_model": {
                "type": "text",
                "label": "Module Fast Model",
                "default": "gemini/gemini-2.5-flash",
                "description": "Lightweight model for module background calls.",
            },
            "retry_attempts": {
                "type": "slider",
                "label": "Retry Attempts",
                "default": 2,
                "min": 1,
                "max": 5,
                "description": "Retries per model before falling back.",
            },
            "retry_delay_seconds": {
                "type": "slider",
                "label": "Retry Delay (s)",
                "default": 1,
                "min": 0,
                "max": 5,
                "description": "Seconds between retry attempts.",
            },
            "temperature": {
                "type": "slider",
                "label": "Temperature",
                "default": 0.9,
                "min": 0,
                "max": 2,
                "step": 0.1,
                "description": "Creativity level. Higher = more creative, lower = more deterministic.",
            },
            "top_p": {
                "type": "slider",
                "label": "Top P",
                "default": 1.0,
                "min": 0,
                "max": 1,
                "step": 0.05,
                "description": "Nucleus sampling threshold.",
            },
            "max_output_tokens": {
                "type": "slider",
                "label": "Max Output Tokens",
                "default": 4096,
                "min": 256,
                "max": 32768,
                "description": "Maximum tokens in the generated response.",
            },
        },
        "presets": [
            {"label": "Gemini 2.5 Flash (Recommended)", "models": {"storyteller_model": "gemini/gemini-2.5-flash", "reader_model": "gemini/gemini-2.5-flash", "embedding_model": "gemini/gemini-embedding-001", "module_fast_model": "gemini/gemini-2.5-flash"}},
            {"label": "Gemini 2.5 Pro", "models": {"storyteller_model": "gemini/gemini-2.5-pro", "reader_model": "gemini/gemini-2.5-flash", "embedding_model": "gemini/gemini-embedding-001", "module_fast_model": "gemini/gemini-2.5-flash"}},
        ],
    },
    "openrouter": {
        "label": "OpenRouter",
        "litellm_prefix": "openrouter",
        "model_fetch_method": "openrouter",
        # The engine's search slot is served by OpenRouter's web plugin
        # (request-level, works with any model — the slot rule holds).
        "supports_search": True,
        "fields": {
            "api_key": {
                "type": "secret",
                "label": "API Key",
                "env_var": "OPENROUTER_API_KEY",
                "required": True,
            },
            "search_enabled": {
                "type": "toggle",
                "label": "Agent Web Search",
                "default": True,
                "description": "Allow AI agents to search the web through OpenRouter's web plugin (Exa engine, ~$0.005 per search billed to your OpenRouter credit).",
            },
            "openrouter_provider": {
                "type": "select",
                "label": "Default Provider",
                "default": "",
                "options": ["", "anthropic", "openai", "google", "meta-llama", "mistralai", "deepseek", "cohere", "x-ai"],
                "description": "Default routing provider (leave empty to let OpenRouter decide).",
            },
            "openrouter_storyteller_provider": {
                "type": "text",
                "label": "Storyteller Provider",
                "default": "",
                "description": "Provider override for the storyteller model slot.",
            },
            "openrouter_fallback_provider": {
                "type": "text",
                "label": "Fallback Provider",
                "default": "",
                "description": "Provider override for the fallback models slot.",
            },
            "openrouter_reader_provider": {
                "type": "text",
                "label": "Reader Provider",
                "default": "",
                "description": "Provider override for the reader model slot.",
            },
            "openrouter_embedding_provider": {
                "type": "text",
                "label": "Embedding Provider",
                "default": "",
                "description": "Provider override for the embedding model slot.",
            },
            "openrouter_fast_provider": {
                "type": "text",
                "label": "Fast Model Provider",
                "default": "",
                "description": "Provider override for the module fast model slot.",
            },
            "storyteller_model": {
                "type": "text",
                "label": "Storyteller Model",
                "default": "claude-sonnet-4-20250514",
                "description": "Model name for the selected provider.",
            },
            "storyteller_fallback_models": {
                "type": "text",
                "label": "Fallback Models",
                "default": "",
                "description": "Comma-separated list of backup models.",
            },
            "reader_model": {
                "type": "text",
                "label": "Reader Model",
                "default": "meta-llama/llama-4-maverick",
                "description": "Model for structured JSON extraction.",
            },
            "embedding_model": {
                "type": "text",
                "label": "Embedding Model",
                "default": "google/text-embedding-004",
                "description": "Model for vector embeddings.",
            },
            "module_fast_model": {
                "type": "text",
                "label": "Module Fast Model",
                "default": "meta-llama/llama-4-maverick",
                "description": "Lightweight model for module background calls.",
            },
            "retry_attempts": {
                "type": "slider",
                "label": "Retry Attempts",
                "default": 2,
                "min": 1,
                "max": 5,
                "description": "Retries per model before falling back.",
            },
            "retry_delay_seconds": {
                "type": "slider",
                "label": "Retry Delay (s)",
                "default": 1,
                "min": 0,
                "max": 5,
                "description": "Seconds between retry attempts.",
            },
            "temperature": {
                "type": "slider",
                "label": "Temperature",
                "default": 0.9,
                "min": 0,
                "max": 2,
                "step": 0.1,
                "description": "Creativity level.",
            },
            "top_p": {
                "type": "slider",
                "label": "Top P",
                "default": 1.0,
                "min": 0,
                "max": 1,
                "step": 0.05,
                "description": "Nucleus sampling threshold.",
            },
            "max_output_tokens": {
                "type": "slider",
                "label": "Max Output Tokens",
                "default": 4096,
                "min": 256,
                "max": 32768,
                "description": "Maximum tokens in the generated response.",
            },
        },
        "presets": [
            {"label": "Claude Sonnet 4 (Recommended)", "config": {"storyteller_model": "anthropic/claude-sonnet-4-20250514", "reader_model": "meta-llama/llama-4-maverick", "embedding_model": "google/text-embedding-004", "module_fast_model": "meta-llama/llama-4-maverick"}},
            {"label": "GPT-4o via OpenRouter", "config": {"storyteller_model": "openai/gpt-4o", "reader_model": "openai/gpt-4o-mini", "embedding_model": "openai/text-embedding-3-small", "module_fast_model": "openai/gpt-4o-mini"}},
            {"label": "Llama 4 Maverick", "config": {"storyteller_model": "meta-llama/llama-4-maverick", "reader_model": "meta-llama/llama-4-maverick", "embedding_model": "google/text-embedding-004", "module_fast_model": "meta-llama/llama-4-maverick"}},
        ],
    },
    "openai": {
        "label": "OpenAI",
        "litellm_prefix": "openai",
        "model_fetch_method": "openai",
        # OpenAI ties web search to specific search-preview models / the
        # Responses API — not wireable model-agnostically, so no search slot.
        "supports_search": False,
        "fields": {
            "api_key": {
                "type": "secret",
                "label": "API Key",
                "env_var": "OPENAI_API_KEY",
                "required": True,
            },
            "storyteller_model": {
                "type": "text",
                "label": "Storyteller Model",
                "default": "openai/gpt-4o",
                "description": "Model for narrative generation. Use openai/ prefix.",
            },
            "storyteller_fallback_models": {
                "type": "text",
                "label": "Fallback Models",
                "default": "",
                "description": "Comma-separated list of backup storyteller models.",
            },
            "reader_model": {
                "type": "text",
                "label": "Reader Model",
                "default": "openai/gpt-4o-mini",
                "description": "Model for structured JSON extraction.",
            },
            "embedding_model": {
                "type": "text",
                "label": "Embedding Model",
                "default": "openai/text-embedding-3-small",
                "description": "Model for vector embeddings.",
            },
            "module_fast_model": {
                "type": "text",
                "label": "Module Fast Model",
                "default": "openai/gpt-4o-mini",
                "description": "Lightweight model for module background calls.",
            },
            "retry_attempts": {
                "type": "slider",
                "label": "Retry Attempts",
                "default": 2,
                "min": 1,
                "max": 5,
                "description": "Retries per model before falling back.",
            },
            "retry_delay_seconds": {
                "type": "slider",
                "label": "Retry Delay (s)",
                "default": 1,
                "min": 0,
                "max": 5,
                "description": "Seconds between retry attempts.",
            },
            "temperature": {
                "type": "slider",
                "label": "Temperature",
                "default": 0.9,
                "min": 0,
                "max": 2,
                "step": 0.1,
                "description": "Creativity level.",
            },
            "top_p": {
                "type": "slider",
                "label": "Top P",
                "default": 1.0,
                "min": 0,
                "max": 1,
                "step": 0.05,
                "description": "Nucleus sampling threshold.",
            },
            "max_output_tokens": {
                "type": "slider",
                "label": "Max Output Tokens",
                "default": 4096,
                "min": 256,
                "max": 32768,
                "description": "Maximum tokens in the generated response.",
            },
        },
        "presets": [
            {"label": "GPT-4o (Recommended)", "models": {"storyteller_model": "openai/gpt-4o", "reader_model": "openai/gpt-4o-mini", "embedding_model": "openai/text-embedding-3-small", "module_fast_model": "openai/gpt-4o-mini"}},
            {"label": "GPT-4.1 Nano (Fast)", "models": {"storyteller_model": "openai/gpt-4.1-nano", "reader_model": "openai/gpt-4.1-nano", "embedding_model": "openai/text-embedding-3-small", "module_fast_model": "openai/gpt-4.1-nano"}},
        ],
    },
    "deepseek": {
        "label": "DeepSeek",
        "litellm_prefix": "deepseek",
        "model_fetch_method": "deepseek",
        "base_url": "https://api.deepseek.com",
        # DeepSeek's API offers no web search.
        "supports_search": False,
        "fields": {
            "api_key": {
                "type": "secret",
                "label": "API Key",
                "env_var": "DEEPSEEK_API_KEY",
                "required": True,
            },
            "storyteller_model": {
                "type": "text",
                "label": "Storyteller Model",
                "default": "deepseek/deepseek-chat",
                "description": "Model for narrative generation. Use deepseek/ prefix.",
            },
            "storyteller_fallback_models": {
                "type": "text",
                "label": "Fallback Models",
                "default": "",
                "description": "Comma-separated list of backup storyteller models.",
            },
            "reader_model": {
                "type": "text",
                "label": "Reader Model",
                "default": "deepseek/deepseek-chat",
                "description": "Model for structured JSON extraction.",
            },
            "embedding_model": {
                "type": "text",
                "label": "Embedding Model",
                "default": "",
                "description": "DeepSeek does not provide embeddings. Use a Gemini or OpenAI model (e.g., gemini/gemini-embedding-001).",
            },
            "module_fast_model": {
                "type": "text",
                "label": "Module Fast Model",
                "default": "deepseek/deepseek-chat",
                "description": "Lightweight model for module background calls.",
            },
            "retry_attempts": {
                "type": "slider",
                "label": "Retry Attempts",
                "default": 2,
                "min": 1,
                "max": 5,
                "description": "Retries per model before falling back.",
            },
            "retry_delay_seconds": {
                "type": "slider",
                "label": "Retry Delay (s)",
                "default": 1,
                "min": 0,
                "max": 5,
                "description": "Seconds between retry attempts.",
            },
            "temperature": {
                "type": "slider",
                "label": "Temperature",
                "default": 0.9,
                "min": 0,
                "max": 2,
                "step": 0.1,
                "description": "Creativity level. Higher = more creative, lower = more deterministic.",
            },
            "top_p": {
                "type": "slider",
                "label": "Top P",
                "default": 1.0,
                "min": 0,
                "max": 1,
                "step": 0.05,
                "description": "Nucleus sampling threshold.",
            },
            "max_output_tokens": {
                "type": "slider",
                "label": "Max Output Tokens",
                "default": 4096,
                "min": 256,
                "max": 32768,
                "description": "Maximum tokens in the generated response.",
            },
        },
        "presets": [
            {"label": "DeepSeek Chat (Recommended)", "models": {"storyteller_model": "deepseek/deepseek-chat", "reader_model": "deepseek/deepseek-chat", "embedding_model": "", "module_fast_model": "deepseek/deepseek-chat"}},
            {"label": "DeepSeek Reasoner", "models": {"storyteller_model": "deepseek/deepseek-reasoner", "reader_model": "deepseek/deepseek-chat", "embedding_model": "", "module_fast_model": "deepseek/deepseek-chat"}},
        ],
    },
    "anthropic": {
        "label": "Anthropic Claude",
        "litellm_prefix": "anthropic",
        "model_fetch_method": "anthropic",
        # Anthropic has a server-side web_search tool, but our litellm path
        # doesn't wire it yet — flip only with an LLMService integration.
        "supports_search": False,
        "fields": {
            "api_key": {
                "type": "secret",
                "label": "API Key",
                "env_var": "ANTHROPIC_API_KEY",
                "required": True,
            },
            "storyteller_model": {
                "type": "text",
                "label": "Storyteller Model",
                "default": "anthropic/claude-sonnet-4-20250514",
                "description": "Model for narrative generation. Use anthropic/ prefix.",
            },
            "storyteller_fallback_models": {
                "type": "text",
                "label": "Fallback Models",
                "default": "",
                "description": "Comma-separated list of backup storyteller models.",
            },
            "reader_model": {
                "type": "text",
                "label": "Reader Model",
                "default": "anthropic/claude-haiku-4-20250514",
                "description": "Model for structured JSON extraction.",
            },
            "embedding_model": {
                "type": "text",
                "label": "Embedding Model",
                "default": "",
                "description": "Anthropic does not provide embeddings. Use a Gemini or OpenAI model (e.g., gemini/text-embedding-004).",
            },
            "module_fast_model": {
                "type": "text",
                "label": "Module Fast Model",
                "default": "anthropic/claude-haiku-4-20250514",
                "description": "Lightweight model for module background calls.",
            },
            "retry_attempts": {
                "type": "slider",
                "label": "Retry Attempts",
                "default": 2,
                "min": 1,
                "max": 5,
                "description": "Retries per model before falling back.",
            },
            "retry_delay_seconds": {
                "type": "slider",
                "label": "Retry Delay (s)",
                "default": 1,
                "min": 0,
                "max": 5,
                "description": "Seconds between retry attempts.",
            },
            "temperature": {
                "type": "slider",
                "label": "Temperature",
                "default": 0.9,
                "min": 0,
                "max": 1,
                "step": 0.1,
                "description": "Creativity level.",
            },
            "top_p": {
                "type": "slider",
                "label": "Top P",
                "default": 1.0,
                "min": 0,
                "max": 1,
                "step": 0.05,
                "description": "Nucleus sampling threshold.",
            },
            "max_output_tokens": {
                "type": "slider",
                "label": "Max Output Tokens",
                "default": 4096,
                "min": 256,
                "max": 32768,
                "description": "Maximum tokens in the generated response.",
            },
        },
        "presets": [
            {"label": "Claude Sonnet 4 (Recommended)", "models": {"storyteller_model": "anthropic/claude-sonnet-4-20250514", "reader_model": "anthropic/claude-haiku-4-20250514", "embedding_model": "", "module_fast_model": "anthropic/claude-haiku-4-20250514"}},
            {"label": "Claude Opus 4", "models": {"storyteller_model": "anthropic/claude-opus-4-20250514", "reader_model": "anthropic/claude-haiku-4-20250514", "embedding_model": "", "module_fast_model": "anthropic/claude-haiku-4-20250514"}},
        ],
    },
}
