"""Lazy child-map expansion tasks: a location opens into its own map (an
interior, a sub-area) generated by ONE full-attention LLM call the first
time the story approaches it, prefetched during travel so multi-turn
journeys hide the latency entirely. Cached per world.

In-flight expansion tasks live on the host: ``host._site_tasks`` (keyed by
anchor node id; the name is historical).
"""

import asyncio
import logging

from . import backfill as _backfill_rt
from . import sync as _sync
from .worldspace import map_of_node, node_index, player_map_id

_logger = logging.getLogger(__name__)

# Automatic prefetch focuses on major places; on-request expansion (the
# enter: token, the map's Explore button) has no importance gate — the AI
# and the player decide what deserves depth.
PREFETCH_IMPORTANCE_FLOOR = 6


def site_mode(host) -> str:
    try:
        if host._services is not None and host._services.get("settings") is not None:
            mode = host._services["settings"].get("world.site_expansion_mode")
            if mode:
                return str(mode)
    except Exception:
        pass
    return "prefetch"


def is_expandable_here(host, wd: dict, map_id: str, node: dict) -> bool:
    try:
        return bool(host.world_builder.is_node_expandable(wd, map_id, node))
    except Exception:
        return False


def maybe_expand_node(host, state: dict, node_id: str, on_request: bool = False):
    """Fire-and-forget child-map expansion for a node (automatic modes only;
    the manual route calls the facade directly). ``on_request`` skips the
    prefetch importance floor — an explicit enter/explore is never refused."""
    if not node_id:
        return
    if not on_request and site_mode(host) not in ("prefetch", "on_arrival"):
        return
    if not _backfill_rt.backfill_available(host, state):
        return
    wd = state.get("world_data")
    if not wd:
        return
    node = node_index(wd).get(node_id)
    if node is None:
        return
    if not on_request and node.get("importance", 0) < PREFETCH_IMPORTANCE_FLOOR:
        return
    map_id = map_of_node(wd, node_id) or player_map_id(state)
    if not is_expandable_here(host, wd, map_id, node):
        return
    existing = host._site_tasks.get(node_id)
    if existing is not None and not existing.done():
        return
    host._site_tasks[node_id] = asyncio.create_task(
        expand_node_task(host, state.get("world_id"), map_id, node_id))


async def expand_node_task(host, world_id: str, map_id: str, node_id: str,
                           must_include: str = None):
    try:
        bundle = await host.world_builder.expand_node(
            world_id, map_id, node_id, must_include=must_include)
        _sync.sync_child_map(host, world_id, bundle)
        await _sync.embed_child_map(host, world_id, bundle)
    except FileNotFoundError:
        host._backfill["disabled"] = True
        _logger.warning("world '%s' missing; map expansion disabled", world_id)
    except Exception:
        _logger.exception("map expansion failed for node %s", node_id)
    finally:
        host._site_tasks.pop(node_id, None)


async def ensure_child_map(host, state: dict, node_id: str, timeout: float = 20,
                           must_include: str = None):
    """Await-on-enter: the player walks into an unmapped place — wait
    (bounded) for its child map so the entrance narration has real rooms. On
    timeout the generation keeps running and lands next turn; returns the
    child map record or None. ``must_include`` folds a place the story
    already went to into a first expansion (ignored when the map exists or
    an expansion is already running)."""
    wd = state.get("world_data")
    if not wd or not node_id:
        return None
    from .worldspace import children_by_anchor, get_map
    map_id = map_of_node(wd, node_id) or player_map_id(state)
    existing = children_by_anchor(wd).get((map_id, node_id))
    if existing:
        return get_map(wd, existing[0])
    if not _backfill_rt.backfill_available(host, state):
        return None
    task = host._site_tasks.get(node_id)
    if task is None or task.done():
        task = asyncio.create_task(
            expand_node_task(host, state.get("world_id"), map_id, node_id,
                             must_include=must_include))
        host._site_tasks[node_id] = task
    try:
        await asyncio.wait_for(asyncio.shield(task), timeout=timeout)
    except asyncio.TimeoutError:
        _logger.warning("timed out waiting for child map of %s; it will land next turn", node_id)
        return None
    except Exception:
        return None
    child_ids = children_by_anchor(wd).get((map_id, node_id)) or []
    return get_map(wd, child_ids[0]) if child_ids else None