"""Lazy site expansion: major locations (cities, ports, strongholds) get their
interior detail — layout + districts/venues — generated by ONE full-attention
LLM call the first time the story approaches them, prefetched during travel
so multi-turn journeys hide the latency entirely. Cached per world.

In-flight expansion tasks live on the host: ``host._site_tasks``.
"""

import asyncio
import logging

from . import backfill as _backfill_rt
from . import sync as _sync
from .worldspace import all_map_nodes

_logger = logging.getLogger(__name__)


def site_mode(host) -> str:
    try:
        if host._services is not None and host._services.get("settings") is not None:
            mode = host._services["settings"].get("world.site_expansion_mode")
            if mode:
                return str(mode)
    except Exception:
        pass
    return "prefetch"


def maybe_expand_site(host, state: dict, node_id: str):
    """Fire-and-forget interior expansion for a major location (automatic
    modes only; the manual route calls the facade directly)."""
    if site_mode(host) not in ("prefetch", "on_arrival") or not node_id:
        return
    if not _backfill_rt.backfill_available(host, state):
        return
    wd = state.get("world_data")
    if not wd or node_id in (wd.get("site_maps") or {}):
        return
    node = next((n for n in all_map_nodes(wd) if n.get("id") == node_id), None)
    if node is None or not host.world_builder.is_site_expandable(node):
        return
    existing = host._site_tasks.get(node_id)
    if existing is not None and not existing.done():
        return
    host._site_tasks[node_id] = asyncio.create_task(
        expand_site_task(host, state.get("world_id"), node_id))


async def expand_site_task(host, world_id: str, node_id: str):
    try:
        site = await host.world_builder.expand_site(world_id, node_id)
        _sync.sync_site(host, world_id, node_id, site)
        await _sync.embed_site(host, world_id, site)
    except FileNotFoundError:
        host._backfill["disabled"] = True
        _logger.warning("world '%s' missing; site expansion disabled", world_id)
    except Exception:
        _logger.exception("site expansion failed for node %s", node_id)
    finally:
        host._site_tasks.pop(node_id, None)
